web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./html:/code
    - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: ./php/.
  volumes: 
    - ./html:/code
    - ./html/php.ini.sample:/usr/local/etc/php/conf.d/php.ini
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    # - maildev

composer:
  build: ./composer/.
  restart: 'no'
  command: install
  volumes:
    - ./html:/app

mysql:
  image: mariadb:latest
  restart: always 
  volumes:
      - ./mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_DATABASE=magnetodb
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin123Z