web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./html:/code
    - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: ./php/.
  volumes: 
    - ./html:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    # - maildev

composer:
  build: ./composer/.
  restart: 'no'
  command: install
  volumes:
    - ./html:/app

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_DATABASE=magnetodb
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin123

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB

# maildev:
#   image: djfarrelly/maildev
#   ports:
# - "8081:80"