web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./html:/code
    - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - ./html:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql
    # - maildev

mysql:
  image: mysql:5.7
  ports:
    - "33006:3306"
  environment: 
    - MYSQL_DATABASE=magnetodb
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=admin123
    - MYSQL_PASSWORD=admin123

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB

# maildev:
#   image: djfarrelly/maildev
#   ports:
# - "8081:80"